motor_ctrl_node:
  ros__parameters:
      cmd_can_id:
        left_hip_pitch: 0x00
        left_knee: 0x01
        right_hip_pitch: 0x02
        right_knee: 0x03
        left_hip_yaw: 0x04
        left_hip_roll: 0x05
        right_hip_yaw: 0x06
        right_hip_roll: 0x07

      feedback_can_id:
        left_hip_pitch: 0x50
        left_knee: 0x51
        right_hip_pitch: 0x52
        right_knee: 0x53
        left_hip_yaw: 0x54
        left_hip_roll: 0x55
        right_hip_yaw: 0x56
        right_hip_roll: 0x57

      kp:
        left_hip_pitch: 2.0
        left_knee: 2.0
        right_hip_pitch: 2.0
        right_knee: 2.0
        left_hip_yaw: 2.0
        left_hip_roll: 2.0
        right_hip_yaw: 2.0
        right_hip_roll: 2.0

      kd:
        left_hip_pitch: 1.0
        left_knee: 1.0
        right_hip_pitch: 1.0
        right_knee: 1.0
        left_hip_yaw: 1.0
        left_hip_roll: 1.0
        right_hip_yaw: 1.0
        right_hip_roll: 1.0
